export enum CommandEnum {
  REQUEST_LOCATION = 0,
  DISPLAY_MESSAGE = 1,
  UPDATE_APP_USAGE_LIMITS = 2,
  UPDATE_GLOBAL_DEVICE_USAGE_LIMIT = 3,
}
export enum CommandStatusEnum {
  COMMAND_RECEIVED = 0,
  COMMAND_FAILED = 1,
  COMMAND_SUCCESS = 2,
}
